### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by rodion-m** [paul-gauthier/refactor-benchmark#1]
Hi @paul-gauthier ! Thanks a lot for a great benchmark. I'd like to suggest to create a leaderboard based on this benchmark, it'll be really really helpful for us, programmers. @paul-gauthier what do we need to implement it?

**Comment by paul-gauthier** [comment]
There's already a leaderboard available:

https://aider.chat/docs/leaderboards/

**Comment by rodion-m** [comment]
Very nice, thanks a lot!

**Comment by jacklxc** [comment]
Hi, is this leaderboard based on single-pass prediction or multiple passes, i.e. retrial after test failure? How many retrials are allowed?

**Comment by paul-gauthier** [comment]
This doc may be helpful:
https://aider.chat/docs/benchmarks.html#the-benchmark
